#!/usr/bin/env sh
# Audit & Hardening by HARRY DS ALSYUNDAWY - ALSYUNDAWY IT SOLUTION (2026)
#
# File search script by <workexp@csc.liv.ac.uk>
# Usage: match [Filename]
#

set -eu

for substring in "$@"; do
    OLD_IFS="$IFS"
    IFS=":"
    # shellcheck disable=SC2086 # Splitting $PATH intentionally
    for path in $PATH; do
        IFS="$OLD_IFS"
        for command in "${path}/"*"${substring}"*; do
            if [ -f "$command" ]; then
                printf "%s\n" "$command"
            fi
        done
        IFS=":"
    done
    IFS="$OLD_IFS"
done

# Added
printf "[%s] PAUSED... Hit return!\n" "$$"
# shellcheck disable=SC2034
read -r DUMMY
